title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://xaramillo.github.io/test-repo-justthedocs

aux_links:
  Template Repository: https://github.com/xaramillo/test-repo-justthedocs
